### ISSUE TITLE
Integer size mismatch between client & server

### ISSUE THREAD

**Issue by jvsg** [abetterinternet/libprio-rs#11]
Client produces share vector with element of size u8, while the server accepts vector with size u32. Seems like a mismatch, unless I am mistaken.

(I am new to rust, so feel free to correct me)

**Comment by jvsg** [comment]
The problem seems here:

```
        let share2 = crate::prng::secret_share(&mut proof);
```

secret_share() return Vec<u8> but it should return Vec<u32>

**Comment by tgeoghegan** [comment]
Thank you for the bug report! I took a long look at what's going on there, and I think there isn't a problem, but I'll try to spell out why so you can tell me if I missed anything important.

`crate::prng::secret_share` takes `proof`, which is `[Field]` (a wrapper around ``u32` which implements finite field arithmetic). It then generates a PRNG seed, represented as a vector of bytes (`Vec<u8>`), generates a `Vec<Field>` of random values from that seed, and finally mutates the `proof` that was passed in by subtracting the vector of random values from the proof vector. `secret_share` then returns the PRNG seed, which is still just a byte vector.

So now the client has the PRNG seed represented as a `Vec<u8>`. It then takes the mutated `proof` vector--still a `[Field]`--and runs it through `util::serialize`, which encodes the `[Field`] as `Vec<u8>`.

So now the client has both data shares encoded as `Vec<u8>`, byte vectors. Share 1 is actually a slice of `Field`, and share 2 is a PRNG seed. On the server side, server 1 will decode the `Vec<u8>` back into `Vec<Field>` (using `util::deserialize`), and server 2 will use the PRNG seed to regenerate the random `Field` values that the client used to mutate the proof earlier.

I'll admit that the behavior of `crate::prng::secret_share()` is kind of confusing. It should probably return a tuple `(Vec<Field>, Vec<u8>)` instead of mutating one of its inputs in-place.

Anyway, does that explanation make sense to you @jvsg?

**Comment by jvsg** [comment]
Thanks for that @tgeoghegan. I've written an [example](https://github.com/abetterinternet/libprio-rs/pull/12) that should help people like me.

I'll close this issue.
