### ISSUE TITLE
Unify and clean up serialization logic

### ISSUE THREAD

**Issue by cjpatton** [abetterinternet/libprio-rs#24]
Data serialization is currently ad-hoc throughout this library. For example, The `FieldElement` trait specifies methods for writing field elements to or reading field elements from a buffer. We would like to replace this with whatever serialization logic is idiomatic for Rust. (See https://github.com/abetterinternet/libprio-rs/pull/22#discussion_r608236929.)

When thinking about how to rework this, we should also think about how protocol messages will be encoded on the wire.

cc/ @acmiyaguchi

**Comment by tgeoghegan** [comment]
We also have this messy business where `util::serialize` and `util::deserialize` convert back and forth between `Vec<F: FieldElement>` and `Vec<u8>`. We then apply a further deserialization step via `unpack_proof[_mut]` to deserialize `[F: Field]` into a Rust struct `UnpackedProof[Mut]`, which somewhat perversely also contains the input share.

I wonder now if all of `util.rs` could be replaced by one or more structs with a better name than `UnpackedProof` (it's obviously unpacked by virtue of being a struct and not just `[u8]`, and it doesn't just contain the proof) that are appropriate decorated with `serde` tags so that we can convert back and forth from byte arrays.

**Comment by acmiyaguchi** [comment]
I've spent some time trying out bincode with structs that implement the serde traits in #29. I'm not sure it's worth pursuing (but I could be convinced otherwise).

It would be nice to use an off-the-shelf data format like bincode, but it performs poorly with the serialization of FieldElements from a u128 into a packed bytearray. It treats arrays as a tuple of (u64, [u8]) which ends up being wider than just storing the u128 alone. One way to overcome this would be to pack the values into an anonymous tuple with an entry for each byte (but there isn't a way to do this without it looking like a big hack). 

The serialize/deserialize methods that exist in utils _could_ adopt traits for Serializer and Deserializer, but it doesn't add any value (e.g. make it easier write language bindings). It's also verbose to boot.

In any case, #27 adds the minimum amount of code for needed for the [serde-serialize feature in wasm-bindgen](https://rustwasm.github.io/docs/wasm-bindgen/reference/arbitrary-data-with-serde.html).

**Comment by cjpatton** [comment]
My main concern is this serialization function in `field.rs` (and its corresponding deserializer, `read_from`):
```rust
fn append_to(&self, bytes: &mut Vec<u8>) {
   // Convert field element to its integer representation
   let int = $fp.from_elem(self.0); 

   // Encode integer as bytes
   let mut slice = [0; Self::BYTES]; 
   for i in 0..Self::BYTES {
       slice[i] = ((int >> (i << 3)) & 0xff) as u8;
    }

    // Append bytes to buffer
    bytes.extend_from_slice(&slice);
}
```
What this function does is extend the buffer with the byte representation of the field element. (Note that `Self::BYTES` doesn't necessarily align with a primitive boundary. 1, 4, 8, 10, and 11 are all valid values; it just depends on the field.) My question is whether there is an idiomatic way to do this in Rust, i.e., whether serde specifies a trait that defines a similar functionality.

If so, then replacing `append_to` with an implementation of said trait may have certain benefits. First, it would allow us to change the wire format without worrying too much about side-effects here. Second, I could imagine that there are certain situations in which `append_to` isn't the most efficient thing. For example, extending the buffer may cause a heap allocation if it exceeds the buffer's capacity.

**Comment by acmiyaguchi** [comment]
Serde does provide a set of relevant traits; for brevity I'll limit discussion to the Serialize and Serializer traits. The Serialize trait tells a Serializer what fields need to be put on the wire. Often the trait can be derived, but in this case we'd want to implement our own.

```rust
impl Serialize for Field32 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where S: Serializer,
    {
        let mut vec = Vec::new();
        self.append_to(&vec);
        serializer.serialize_bytes(&vec)
    }
}
```

Now a library like `serde_json` or `bincode` can implement a Serializer that maps to a particular data format. `bincode` will treat this as `(u64, [u8])` for a total of 8 + 4 bytes serialized to disk, since sequence types (e.g. `&u[8]`) are always concatenated with their length. This is more apparent if you tried to serialize `Vec<FieldElement>`.

```rust
---- field::tests::test_field32 stdout ----
thread 'field::tests::test_field32' panicked at 'assertion failed: `(left == right)`
  left: `12`,
 right: `4`', src/field.rs:479:13

---- field::tests::test_field64 stdout ----
thread 'field::tests::test_field64' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `8`', src/field.rs:479:13

---- field::tests::test_field80 stdout ----
thread 'field::tests::test_field80' panicked at 'assertion failed: `(left == right)`
  left: `18`,
 right: `10`', src/field.rs:479:13

---- field::tests::test_field126 stdout ----
thread 'field::tests::test_field126' panicked at 'assertion failed: `(left == right)`
  left: `24`,
 right: `16`', src/field.rs:479:13
```

To avoid the overhead, we'd have to implement the Serializer interface itself:

```rust
pub struct Serializer {
    output: Vec<u8>,
}

impl<'a> ser::Serializer for &'a mut Serializer {
    type Ok = ();
    type Error = Error;
    fn serialize_bytes(self, v: &[u8]) -> Result<()> {
        self.output.extend(v)
    }
}

pub fn to_bytes<T>(value: &T) -> Result<[u8]>
where
    T: Serialize,
{
    let mut serializer = Serializer { output: Vec::new() };
    value.serialize(&mut serializer)?;
    Ok(serializer.output)
}
```

The full trait needs to be implemented (setting unused ones with `!unimplemented()`). In the end, the serializer would be used to pack a struct like `UnpackedProof<F: FieldElement>` directly into bytes. We'd also have to implement the deserializer interface too. Then we'd have some functions that look like the following that would be generically work on the Serialize trait.

```rust
pub mod ser {
   pub fn to_bytes<T>(value: &T) -> Result<[u8]> where T: Serialize;
}
```

In short, the problem is that serializers like bincode or serde_json will increase the size of the payload if represented as a byte array. This can be solved by writing a custom serializer which means the general logic stays the same (unpack_proof, serialize, etc), just with a more verbose interface. I'm not sure this is worthwhile whether it be to increase the size of the payload by adopting bincode (or alternative), implement serialize for each struct that uses FieldElement to concatenate sequences of elements, or to implement a serializer for a custom (but compact) payload format.

<details>
<summary>Appendix of dead-end ideas</summary>

Alternatively, it might be possible with clever macro usage to pack the u128 into a tuple of fixed size. This would mean composition of the FieldElements would be more efficient (although the actual proof shares will still be an extra 8 bytes wider for each array in the container struct).

```rust
impl Serialize for Field32 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where S: Serializer,
    {
        // this would need to have the same number of elements as $bytes from the macro invocation
        #[derive(Serialize)]
        struct Container(u8, u8, u8, u8);
        let mut vec = Vec::new();
        self.append_to(&vec);
        // TODO: initialize the container tuple from the vec
        let container = ....
        // Serialize before passing 
        serializer.serialize_bytes(bincode::serialize(&container).unwrap())
    }
}
```

But, this has the same problem as before since it's still using the serialize_bytes interface. Maybe this?

```rust
Field32 {
  #[serde(skip_serializing)]
  elem: u128,
  container: struct(u8, u8, u8, u8),
};
```

This is less than ideal, and requires the container struct to be up to date with the elem.

</details>

**Comment by cjpatton** [comment]
Thanks for looking into this @acmiyaguchi! It may be worth implementing custom serializers, but we can consider doing so later. I suggest we keep the issue open in the meantime.

**Comment by cjpatton** [comment]
@tgeoghegan can we close this one?

**Comment by tgeoghegan** [comment]
I think so. We've got `serde::{Serialize, Deserialize}` implementations on enough of the structs in crate `prio` that I was able to implement `ppm-protoype` and serialize everything to JSON. Picking or implementing a Serde data format for whatever wire encoding we end up choosing should be done outside of `libprio-rs` anyway.
