### ISSUE TITLE
Benchmarking the scalability of the current implementation

### ISSUE THREAD

**Issue by rsk97** [abetterinternet/libprio-rs#42]
Given the use of the work, will we be able to benchmark the number of clients that 2 servers can support. Ideally, benchmark the performance and share the hardware specifications of the servers and data load shared by the client.

**Comment by rsk97** [comment]
Thanks a lot! If the data flowing from the clients were say 0 or 1 and I plan to use it across a million devices and say 2 servers. Will I be able to simulate this expt on my machine? If so are there any starter guides to it?

Also, can you please mention the difference between `v3` and `v2` of the proof generations?
Does `size` in this output refer to the size of the data transferred or the proof string or is it the number of clients?

Thanks for your time! I am very new to this, thanks for your quick response!

**Comment by cjpatton** [comment]
> Thanks a lot! If the data flowing from the clients were say 0 or 1 and I plan to use it across a million devices and say 2 servers. Will I be able to simulate this expt on my machine? If so are there any starter guides to it?

Well, you're going to quickly choke your CPU if you try to simulate the clients. Indeed, this wouldn't be a realistic simulation because the clients would all be have their own CPUs. On the other hand, you could realistically simulated the servers on pre-generated inputs. To start, you might check out ISRG's server implementation here: https://github.com/abetterinternet/prio-server

> Also, can you please mention the difference between `v3` and `v2` of the proof generations?

Sure! This is a bit confusing I realize. These are terms we're using to refer to proof systems implemented in this crate. We don't intend to use them indefinitely. You should keep in mind that much of this crate is under active development and parts of it are highly unstable (particularly `v3`).

* `v2` refers to the proof system implemented in  `prio::client` (proof generation) and `prio::server` (proof verification). While based on a more general-purpose proof system (see [BBC+19]), `v2` is designed an optimized to prove validity of a secret-shared bit vector (i.e., your use case). Compared to `v3`, this module has had more security review and should be considered more stable.

* `v3` refers to the proof system implemented in `prio::pcp` (both proof generation and verification). This system provides the full functionality of [BBC+19]. In particular, other data types besides bit vectors are supported: integer vectors, histograms,  count-min sketches, etc. This code is relatively new: Compared to `v2`, this module has had less security review and should be considered less stable.


> Does `size` in this output refer to the size of the data transferred or the proof string or is it the number of clients?

In `bool vec v2 prove, size=10000`, `size` refers to the number of field elements of the input bit vector; in `bool vec v2 proof size=26387`, `size` refers to the number of field elements that comprise the proof.


____
[BBC+19] https://eprint.iacr.org/2019/188

**Comment by rsk97** [comment]
@cjpatton - Thanks for the reply and the pointers - I will check the paper out as well!

> Well, you're going to quickly choke your CPU if you try to simulate the clients. Indeed, this wouldn't be a realistic simulation because the clients would all be have their own CPUs. On the other hand, you could realistically simulated the servers on pre-generated inputs. To start, you might check out ISRG's server implementation here: https://github.com/abetterinternet/prio-server

This makes sense! Thanks! Additionally, are there some studies that look at the number of clients possible to simulate on a system with 8 cores!

I am looking to have a basic implementation of say 100 clients 2 servers -> each client shares the data 0/1 and I want to create a heatmap out of it. I will check out the `prio-sever` code you shared. If there are other starter materials for this, it would be great! Thanks!

**Comment by cjpatton** [comment]
@rsk97 take a look at the new vdaf::suite module and see if this will suite your needs.

**Comment by cjpatton** [comment]
`cargo bench --all-features` provides benchmarks for a variety of Prio-based constructions. These ought to address this issue thoroughly enough.
